### ISSUE TITLE
Change background of dashboard on gray

### ISSUE THREAD

**Issue by vadim9999** [atherdon/dashb#104]
![image](https://user-images.githubusercontent.com/35640573/107551617-2b18fd80-6bdb-11eb-9a57-4759457e56f5.png)

**Comment by master-bogdan** [comment]
@vadim9999 which color must be ?

**Comment by vadim9999** [comment]
@master-bogdan I haven't assigned this task to you. Have you done with keywords?

**Comment by vadim9999** [comment]
@master-bogdan replace white color on gray antd background color
