### ISSUE TITLE
Top Authors add a checkbox for V column

### ISSUE THREAD

**Issue by vadim9999** [atherdon/dashb#108]
![image](https://user-images.githubusercontent.com/35640573/105212506-9cc2d600-5b5e-11eb-8c07-d66ade305c6f.png)

**Comment by vadim9999** [comment]
@master-bogdan can't find your changes
![image](https://user-images.githubusercontent.com/35640573/106298498-0466d880-6265-11eb-85ce-8769412f1da6.png)
have you pushed your changes?

**Comment by master-bogdan** [comment]
@vadim9999 I will make some more changes and push it today or tomorrow

**Comment by vadim9999** [comment]
@master-bogdan I have just added authentication and added account for testing. @atherdon Arthur will give you that creds

**Comment by master-bogdan** [comment]
@vadim9999 ok, thanks!

**Comment by vadim9999** [comment]
@master-bogdan have you done this? You can move this card in testing in case you have done it then I'll check it

**Comment by master-bogdan** [comment]
@vadim9999 Yes, I am done this and breadcrumbs
