### ISSUE TITLE
мастер ветка сломана

### ISSUE THREAD

**Issue by coder-do** [atherdon/dashb#129]
После того как запускаю код сразу происходит редирект на другую страницу и сразу выводит ошибку.  Точно не знаю после какого пулла сломался но факт что не работает. (по моему после добавки auth компонента) но могу ошибаться.

**Comment by vadim9999** [comment]
@coder-do да так и есть, тебе нужно создать .env с переменными, напиши @atherdon чтобы он предоставил тебе все креды
