### ISSUE TITLE
editorial reports [not finished]

### ISSUE THREAD

**Issue by atherdon** [atherdon/dashb#17]
attach latest reports
show a table with numbers and how  to calculate that

**Comment by atherdon** [comment]
![1](https://user-images.githubusercontent.com/1469198/103158740-ea4f5b80-47c9-11eb-82bd-1fcd668019a9.png)
![2](https://user-images.githubusercontent.com/1469198/103158742-ee7b7900-47c9-11eb-9b62-27ec4057fabd.png)
![3](https://user-images.githubusercontent.com/1469198/103158744-ef140f80-47c9-11eb-904e-a2f6b61c88a0.png)
![4](https://user-images.githubusercontent.com/1469198/103158746-efaca600-47c9-11eb-88ac-4714a6b2a280.png)

**Comment by atherdon** [comment]
изображение из excel
![image](https://user-images.githubusercontent.com/1469198/103159010-e8d36280-47cc-11eb-809a-b676701e8a99.png)

**Comment by atherdon** [comment]
быстро скопировать у меня не получилось, поэтому я просто сделал экспорт файла и залил его в наш репозиторий: https://github.com/atherdon/dashb/blob/main/docs/Report%20Only%20(1).xlsx

**Comment by atherdon** [comment]
список категорий которые мы отслеживаем

Programming | Python | Blockchain | Amazon | Business | Entrepreneurship | Repost | Security | Ai | Old articles | Brands | Top Authors

**Comment by F1reMonster** [comment]
added  without diagrams

**Comment by F1reMonster** [comment]
added simply diagrams with charts.js
