### ISSUE TITLE
can we use css, that generated by ant-design library and save some time?

### ISSUE THREAD

**Issue by atherdon** [atherdon/dashb#18]
если основной фрилансер программист возглавит проект по переносу верстки в react, он будет использовать ant-design components для некоторых базовых страниц.

есть пару страниц\layouts которые мы бы могли взять и не тратить на них сейчас время.
заодно они красивые, и будет казаться что мы много работы сделали :)

1. нам нужен будет календарь, для того, чтобы было видно сколько статей будет выходить в течении месяца.

2. чтобы не выводить 200-300 статей в одной таблице, я бы разбил их на мелкие части.
и их можно было бы разбить на "stages".

---

1. календарь у ant-d показан на этой [странице](https://ant.design/components/calendar/)
а тут есть codepen с [примерчиком](https://codepen.io/ArtTka/pen/LYROXbE?editors=0010)
тоесть если мы сможем просто скопировать этот код и вставить его в наши страницы - этого вначале будет достаточно.

код из dist я наверное смогу достать. но в гитхабе у них эта папка в игноре, поэтому надо будет скачать компоненты локально и сделать билд. если надо - скажете.

2. второго компонента с коробки, чтобы работал как нам надо - нету, но можно посмотреть на логику на этой [странице ](https://ant.design/components/steps/)

**Comment by atherdon** [comment]
архив, который я скачал с codepen - calendar [notice-calendarantd-4-9-4.zip](https://github.com/atherdon/dashb/files/5743832/notice-calendarantd-4-9-4.zip)

**Comment by F1reMonster** [comment]
календар готовий, стилі так як і html взяті із ant-d

**Comment by atherdon** [comment]
пример со steps: https://codepen.io/ArtTka/pen/eYdyzGx?editors=0010

**Comment by atherdon** [comment]
completed
