### ISSUE TITLE
homepage checker [html]

### ISSUE THREAD

**Issue by atherdon** [atherdon/dashb#190]
![dashb2](https://user-images.githubusercontent.com/1469198/109327242-c9a29100-7860-11eb-96c4-f518f5dad475.png)

т.к. сейчас у нас нету дизайн темы своей(пока еще) - будем делать эту страницу - используя компоненты из ant-design.
код мы перенесли в https://github.com/atherdon/dashb/tree/main/frontend

делаем пока отдельной страницей

**Comment by F1reMonster** [comment]
додав даний шаблон homepage-checker.html

**Comment by atherdon** [comment]
> додав даний шаблон homepage-checker.html

немогу принять пулл - пишет конфликты

**Comment by atherdon** [comment]
готово
