### ISSUE TITLE
electronic queue

### ISSUE THREAD

**Issue by atherdon** [atherdon/dashb#191]
![_](https://user-images.githubusercontent.com/1469198/109327588-2aca6480-7861-11eb-984e-ef461388eb1b.jpg)

тоже делаем, используя дизайн который есть в ant-design для попапов.

нужно получается 2 версии - первая - пока не введены данные. 
и вторая версия - с ответом, какое место у твоей статьи.

**Comment by F1reMonster** [comment]
додав два модальні вікна

**Comment by atherdon** [comment]
готово
