### ISSUE TITLE
[ant d] simple tables with links

### ISSUE THREAD

**Issue by atherdon** [atherdon/dashb#24]
хочу попробывать вывести данные, которые редакторы хранят в экселе, для удобства.

компонент: https://ant.design/components/table/

Ничего особенного пока ненужно, чекбокс можно заменить пока на TRUE и будет ок.
скрин 
![image](https://user-images.githubusercontent.com/1469198/103207378-cf363600-4906-11eb-86f8-a3b1c9c0f52e.png)

аттачу excel file c копией
[Ant D Tables Sample.xlsx](https://github.com/atherdon/dashb/files/5746902/Ant.D.Tables.Sample.xlsx)

**Comment by F1reMonster** [comment]
added tables.html
