### ISSUE TITLE
Data for table(s)

### ISSUE THREAD

**Issue by vadim9999** [atherdon/dashb#43]

**Comment by atherdon** [comment]
[Copy of Brands for csv.zip](https://github.com/atherdon/dashb/files/5777164/Copy.of.Brands.for.csv.zip)
[Copy of Top Authors for CSV.zip](https://github.com/atherdon/dashb/files/5777165/Copy.of.Top.Authors.for.CSV.zip)

**Comment by atherdon** [comment]
@vadim9999 

https://github.com/atherdon/dashb/blob/main/docs/top-authors.js
https://github.com/atherdon/dashb/blob/main/docs/brands.js
