### ISSUE TITLE
keyword checker page [HTML]

### ISSUE THREAD

**Issue by atherdon** [atherdon/dashb#53]
we need to have a way to check some keywords quickly, without a lot of problem or without wasting a lot of time

**Comment by atherdon** [comment]
мы скопировали компонент table, который находится на странице tables.html

1. нужно добавить еще страниц, которые будут отображать другие данные из json. данные хранятся в [этой папке](https://github.com/atherdon/dashb/tree/main/docs/keywrds/data/json)
- Devices
- Filters
- Dates
- Countries
- Pages
- Queries
- Search-appearance

**Comment by atherdon** [comment]
@F1reMonster можете посмотреть, когда будет время?

**Comment by F1reMonster** [comment]
додав дані сторінки

**Comment by atherdon** [comment]
@F1reMonster можно вас попросить переименовать немного сгенерированные страницы, чтобы мне проще было их видеть в папке dist.

например, dates можно переименовать в z-keywords-dates.html и т.д. тогда остальные страницы тоже будут отображаться внизу папки

**Comment by atherdon** [comment]
2. нам нужен search field для каждой из новых страниц. работать он не должен - просто visual representation
я нашел вот такой пример, если он поможет - будет гуд.

https://codesandbox.io/s/z3ln7y0p04

сс @F1reMonster

**Comment by atherdon** [comment]
#64 done

**Comment by F1reMonster** [comment]
> @F1reMonster можно вас попросить переименовать немного сгенерированные страницы, чтобы мне проще было их видеть в папке dist.
> 
> например, dates можно переименовать в z-keywords-dates.html и т.д. тогда остальные страницы тоже будут отображаться внизу папки

перейменував

**Comment by F1reMonster** [comment]
> 1. нам нужен search field для каждой из новых страниц. работать он не должен - просто visual representation
>    я нашел вот такой пример, если он поможет - будет гуд.
> 
> https://codesandbox.io/s/z3ln7y0p04
> 
> сс @F1reMonster

додав

**Comment by atherdon** [comment]
поидее готово. закрываю таск
