### ISSUE TITLE
bad keywords form [not finished]

### ISSUE THREAD

**Issue by atherdon** [atherdon/dashb#6]
similar to 
![image](https://user-images.githubusercontent.com/1469198/103111311-485a3280-4654-11eb-9e9a-a960360087bf.png)

- when a form was submitted - animation should add a keyword to the bottom
- another animation should be, when you click on "x" button - it should hide that keyword

**Comment by atherdon** [comment]
list of bad keywords
- gambling
- slots
- casino
- poker
- outsource company
- outsourcing
- development company
- software company
- application development
- app developers
- magento development company
- essay writing
- copywriting
- blogging
- PIM
- RPA
- Instagram
- SEO
- Google Search
- Google Rank
- Search Engine
- Buy
- Hashtagsforlikes

**Comment by F1reMonster** [comment]
added form with words like screenshot

**Comment by atherdon** [comment]
can you replace keywords with https://github.com/atherdon/dashb/issues/6#issuecomment-751358038 please

**Comment by F1reMonster** [comment]
> can you replace keywords with [#6 (comment)](https://github.com/atherdon/dashb/issues/6#issuecomment-751358038) please

fixed

**Comment by atherdon** [comment]
somethings went wrong @F1reMonster 
![image](https://user-images.githubusercontent.com/1469198/103160923-71f59400-47e3-11eb-8a54-1bd01bfa4334.png)

**Comment by F1reMonster** [comment]
останній пул, поправив

**Comment by atherdon** [comment]
пулл принял. тогда пока закрываю этот таск, а уже позже сделаю более детальное описание, связанное с этим функционалом. пока нам этого достаточно чтобы показать

**Comment by atherdon** [comment]
сейчас архив отправил девелоперу. если у него будут вопросы - напишу
