### ISSUE TITLE
replace true on checkboxes

### ISSUE THREAD

**Issue by vadim9999** [atherdon/dashb#70]
Replace TRUE tag into checkbox in table on page TopAuthors 
![image](https://user-images.githubusercontent.com/35640573/104849908-5fabd900-58fd-11eb-9445-465c465b002f.png)

**Comment by master-bogdan** [comment]
@vadim9999 Also do this on StepsPage ?

**Comment by master-bogdan** [comment]
@vadim9999 checkbox must be like icon, or it must be with checkbox function ?

**Comment by vadim9999** [comment]
@master-bogdan yes, just add checkbox from antd and change his state related to received data from file is it true or not
