### ISSUE TITLE
create card keyword with z-keywords tables

### ISSUE THREAD

**Issue by vadim9999** [atherdon/dashb#72]
Card Keywords already exist. Create page Keywords with all 7 tables and link this page with card Keywords. This html files are like a design. 

![image](https://user-images.githubusercontent.com/35640573/104850792-3477b880-5902-11eb-88d3-c04343051c0b.png)

Store this data in data folder
![image](https://user-images.githubusercontent.com/35640573/104850873-b10a9700-5902-11eb-8eeb-740231db17ee.png)

**Comment by atherdon** [comment]
I think it's completed
