### ISSUE TITLE
Create Progress bar page

### ISSUE THREAD

**Issue by vadim9999** [atherdon/dashb#77]
Create Progress bar page that contains three progress components from antd library. And add new card to dashboard that opens this page.
https://github.com/atherdon/dashb/blob/main/frontend/dist/progress.html
![image](https://user-images.githubusercontent.com/35640573/104748309-a1544c80-5762-11eb-81af-0281a1aa3100.png)

Create our customized Proggress bar component in folder components and use it in Progress bar page

**Comment by vadim9999** [comment]
@master-bogdan we have deleted scss files from react version and added styled components

**Comment by vadim9999** [comment]
@master-bogdan please work with develop branch

**Comment by vadim9999** [comment]
@master-bogdan use github Projects kanban for better understand with progress

**Comment by atherdon** [comment]
@master-bogdan can you also add to this page a table with information, related to each editor performance per week
data isn't clean, but it's a quick starting point for us
https://github.com/atherdon/dashb/blob/main/frontend/docs/editors.js

**Comment by master-bogdan** [comment]
@atherdon yes, i will change data for component

**Comment by atherdon** [comment]
thanks!

**Comment by atherdon** [comment]
@master-bogdan did you add that table component, right?

**Comment by master-bogdan** [comment]
@atherdon Yes I did

**Comment by atherdon** [comment]
cool-thanks let me check it then
