### ISSUE TITLE
brands the same as top authors

### ISSUE THREAD

**Issue by vadim9999** [atherdon/dashb#78]
1. Copy paste brands.js file into data folder. 

![image](https://user-images.githubusercontent.com/35640573/104750334-fee99880-5764-11eb-9391-34bc12935a1c.png)

2. Create page Brands with table in components. Do this like TopAuthors.

3, Add link to the second card

**Comment by atherdon** [comment]
I think it's a pretty simple task, I can't add here anything more.
Right now our goal is to create a separate page/view for displaying that information.
But later, I'm sure, we'll have different fields, sources, etc. so it should be very separate thing
