### ISSUE TITLE
Layout component & top bar menu

### ISSUE THREAD

**Issue by master-bogdan** [atherdon/dashb#85]
@vadim9999 
How about to create top-bar menu and layout HOC ?

**Comment by master-bogdan** [comment]
@atherdon

**Comment by vadim9999** [comment]
@master-bogdan all designs and other feature must answer @atherdon

**Comment by master-bogdan** [comment]
@atherdon we need you here)

**Comment by atherdon** [comment]
yes, lets do a header menu. I think it's time to do it
