### ISSUE TITLE
trying to deploy with vercel and get this error

### ISSUE THREAD

**Issue by atherdon** [atherdon/dashb#90]
![image](https://user-images.githubusercontent.com/1469198/104850610-be228880-58f8-11eb-9628-290bd2efd3cb.png)

**Comment by vadim9999** [comment]
@atherdon open Telegram we will discuss it

**Comment by atherdon** [comment]
i was drinking

**Comment by atherdon** [comment]
why not here?

**Comment by atherdon** [comment]
@vadim9999 i think it works right now. so i'm closing this task
link: https://dashb.atherdon.vercel.app/keywords
